project:
  type: website

website:
  title: ""
  search: true
  google-analytics: "G-PZG13ETS1Z" 

  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      
    tools:
      - icon: youtube
        href: https://www.youtube.com/@Prof.Iguana
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/loweas/CR
          - text: Report a Bug
            href:  https://github.com/loweas/CR/issues

format:
  html:
    theme: cosmo
    toc: true
    toc-location: left
    toc-depth: 4
    toc-expand: true       # <-- THIS makes first-level headings expandable
    sidebar: true
    code-fold: true
    code-summary: "Show code"
    page-layout: full

editor: visual

